data-service/src/main/java/com/nova/dataservice/controller/PromotionController.java
data-service/src/main/java/com/nova/dataservice/entity/Pramotions.java
data-service/src/main/java/com/nova/dataservice/repository/PromotionsRepository.java
data-service/src/main/java/com/nova/dataservice/service/PromotionsServices.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/Promotionsserviceimpl.java

API(FIRST-25) get promotion by shopId

API(FIRST-25) get promotion by shopId

---

NovaMailSender/src/main/java/com/nova/mail/controller/MailController.java
OwnerApp/src/main/java/com/nova/Owner/Controller/AppointmentCountByShopIdController.java
OwnerApp/src/main/java/com/nova/Owner/Controller/OwnerController.java
OwnerApp/src/main/java/com/nova/Owner/Controller/ShopSummaryController.java
data-service/src/main/java/com/nova/dataservice/controller/AppointmentDetailsController.java
data-service/src/main/java/com/nova/dataservice/controller/MasterParameterSubParameterController.java
data-service/src/main/java/com/nova/dataservice/controller/PromotionController.java
data-service/src/main/java/com/nova/dataservice/controller/RoleController.java
data-service/src/main/java/com/nova/dataservice/controller/ServiceMasterController.java
data-service/src/main/java/com/nova/dataservice/controller/ServiceMasterParameterController.java
data-service/src/main/java/com/nova/dataservice/controller/ShopDetailsController.java
data-service/src/main/java/com/nova/dataservice/controller/ShopRatingController.java
data-service/src/main/java/com/nova/dataservice/controller/ShopServiceRelationController.java
data-service/src/main/java/com/nova/dataservice/controller/ShopTypeController.java
data-service/src/main/java/com/nova/dataservice/controller/ShopUpdatedRequestController.java
data-service/src/main/java/com/nova/dataservice/controller/ShopsAvailabilityController.java
data-service/src/main/java/com/nova/dataservice/controller/SlotAvailabilityController.java
data-service/src/main/java/com/nova/dataservice/controller/UserDetailsController.java
nova-report-service/src/main/java/com/nova/demo/controller/PdfController.java
system-config/src/main/java/com/nova/demo/controller/AppConOwnShopController.java
system-config/src/main/java/com/nova/demo/controller/UsersDetailsController.java

@santoshsh2307 
Added RequestMapping to All Controllers

First-16:(Added RequestMapping to All Controllers)

---

data-service/src/main/java/com/nova/dataservice/DTO/AppoinmentDetailDTO.java
data-service/src/main/java/com/nova/dataservice/controller/AppointmentDetailsController.java
data-service/src/main/java/com/nova/dataservice/dao/AppointmentDetailDAO.java
data-service/src/main/java/com/nova/dataservice/daoimpl/AppoinmentDetailDaoImpl.java
data-service/src/main/java/com/nova/dataservice/daoimpl/AppointmentDaoImpl.java
data-service/src/main/java/com/nova/dataservice/service/AppointmentDetailservice.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/AppointmentDetailsserviceimpl.java

This API retrieves all services associated with a specific appointment and patient, providing a comprehensive overview of the services rendered during a particular healthcare interaction.

getAllServicesByAppointmentIdAndPatientId

---

data-service/src/main/java/com/nova/dataservice/DTO/ServiceDetailDTO.java
data-service/src/main/java/com/nova/dataservice/controller/ServiceMasterController.java
data-service/src/main/java/com/nova/dataservice/dao/ServiceDetaildao.java
data-service/src/main/java/com/nova/dataservice/daoimpl/ServiceDetailDaoImpl.java
data-service/src/main/java/com/nova/dataservice/service/ServiceMasterService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/ServiceMasterServiceImpl.java
data-service/src/main/resources/application.yml
spring-gateway/.project

This API retrieves a list of all services associated with a specific laboratory identified by the provided Lab ID.

getAllServicesByLabId

---

data-service/src/main/java/com/nova/dataservice/controller/EmployeTrackingController.java
data-service/src/main/java/com/nova/dataservice/entity/EmployeTracking.java
data-service/src/main/java/com/nova/dataservice/repository/EmployeTrackingRepository.java
data-service/src/main/java/com/nova/dataservice/service/EmployeTrackingService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/EmployeTrackingServiceImpl.java

I have written API for EmployeTracking please Review my code and let me know if there is any changes.

EmployeTrackingAPI

---

data-service/src/main/java/com/nova/dataservice/DTO/TrackingDTO.java
data-service/src/main/java/com/nova/dataservice/controller/EmployeTrackingController.java
data-service/src/main/java/com/nova/dataservice/dao/EmployeTrackingDao.java
data-service/src/main/java/com/nova/dataservice/daoimpl/EmployeTrackingDaoImpl.java
data-service/src/main/java/com/nova/dataservice/entity/EmployeeDetails.java
data-service/src/main/java/com/nova/dataservice/entity/ShopDetails.java
data-service/src/main/java/com/nova/dataservice/repository/EmployeTrackingRepository.java
data-service/src/main/java/com/nova/dataservice/service/EmployeTrackingService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/EmployeTrackingServiceImpl.java

Hi Santosh plz review this code and logic applied in DaoImpl layer and let me know if any changes

getEmployeeDetailsByShopIAndOwnerId API

---

data-service/src/main/java/com/nova/dataservice/DTO/PatientDetailsDTO.java
data-service/src/main/java/com/nova/dataservice/controller/PatientDetailsController.java
data-service/src/main/java/com/nova/dataservice/dao/PatientDetailsDao.java
data-service/src/main/java/com/nova/dataservice/daoimpl/PatientDetailsDaoImpl.java
data-service/src/main/java/com/nova/dataservice/service/AppointmentDetailservice.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/AppointmentDetailsserviceimpl.java

get the  patient data getpatientDetailsByAppointmentId through this api

FIRST-78(1)

---

data-service/src/main/java/com/nova/dataservice/controller/TechnicianDetailsController.java
data-service/src/main/java/com/nova/dataservice/entity/TechnicianDetails.java
data-service/src/main/java/com/nova/dataservice/repository/TechnicianDetailsRepository.java
data-service/src/main/java/com/nova/dataservice/service/TechnicianDetailsService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/TechnicianDetailsServiceImpl.java

Save Notes by Technician for patient

FIRST-78(2)

---

data-service/src/main/java/com/nova/dataservice/controller/InventoryShopRelationController.java
data-service/src/main/java/com/nova/dataservice/controller/TechnicianDetailsController.java
data-service/src/main/java/com/nova/dataservice/repository/InventoryShopRelationRepository.java
data-service/src/main/java/com/nova/dataservice/repository/TechnicianDetailsRepository.java
data-service/src/main/java/com/nova/dataservice/service/TechnicianDetailsService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/InventoryShopRelationServiceImpl.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/TechnicianDetailsServiceImpl.java

get All technician notes by appointmentId and technicianId is done

NOVACARD-116

---

data-service/src/main/java/com/nova/dataservice/DTO/PatientDetailsDTO.java
data-service/src/main/java/com/nova/dataservice/daoimpl/PatientDetailsDaoImpl.java

add the patientName in the API getPatientDetailsByAppointmentId

NOVACARD-114

---

data-service/src/main/java/com/nova/dataservice/controller/InventoryShopRelationController.java
data-service/src/main/java/com/nova/dataservice/entity/TechnicianDetails.java
data-service/src/main/java/com/nova/dataservice/repository/InventoryShopRelationRepository.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/TechnicianDetailsServiceImpl.java

add the appointmentId in technitianDetails table

NOVACARD-115

---

data-service/src/main/java/com/nova/dataservice/controller/ProfileUploadController.java
data-service/src/main/java/com/nova/dataservice/controller/ShopDetailsController.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/ShopDetailsServiceImpl.java

upload profilePhoto in local directory

NOVACARD-95

---

data-service/src/main/java/com/nova/dataservice/controller/DocumentController.java
data-service/src/main/java/com/nova/dataservice/entity/Document.java
data-service/src/main/java/com/nova/dataservice/repository/DocumentRepository.java
data-service/src/main/java/com/nova/dataservice/service/DocumentService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/DocumentServiceImpl.java

FIRST-78(5)

---

data-service/src/main/java/com/nova/dataservice/controller/LabReportLocation.java
data-service/src/main/java/com/nova/dataservice/entity/LabReportLocatiosn.java
data-service/src/main/java/com/nova/dataservice/repository/LabReportLocationReporitory.java
data-service/src/main/java/com/nova/dataservice/service/LabReportLocationService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/LabReportLocationServiceImpl.java

Upload Lab Reports with Patient ID, Technician ID, Appointment ID and lab ID

NOVACARD-117

---

data-service/src/main/java/com/nova/dataservice/DTO/AccessPermissionsDTO.java
data-service/src/main/java/com/nova/dataservice/DTO/UserDetailsDTO.java
data-service/src/main/java/com/nova/dataservice/controller/AccessPermissionsController.java
data-service/src/main/java/com/nova/dataservice/entity/AccessPermissions.java
data-service/src/main/java/com/nova/dataservice/repository/AccessPermissionsRepository.java
data-service/src/main/java/com/nova/dataservice/service/AccessPermissionsService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/AccessPermissionsImpl.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/UserDetailsServicesimpl.java

NOVACARD-119

---

data-service/pom.xml
data-service/src/main/java/com/nova/dataservice/controller/BarCodeGenerateForLabController.java
data-service/src/main/java/com/nova/dataservice/entity/BarCodeGenerateForLabEntity.java
data-service/src/main/java/com/nova/dataservice/repository/BarCodeGenerateForLabRepository.java
data-service/src/main/java/com/nova/dataservice/service/BarCodeGenerateForLabService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/BarCodeGenerateForLabServiceImpl.java

BarCodeGenerated

---

data-service/src/main/java/com/nova/dataservice/controller/PdfLabReportGenaratorController.java
data-service/src/main/java/com/nova/dataservice/controller/ShopDetailsController.java
data-service/src/main/java/com/nova/dataservice/repository/ShopDetailsRepository.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/ShopDetailsServiceImpl.java
data-service/src/main/resources/application.yml

get all the lab details by owner id (Check True or False)

NOVACARD-126

---

data-service/src/main/java/com/nova/dataservice/controller/LabReportLocation.java
data-service/src/main/java/com/nova/dataservice/repository/LabReportLocationReporitory.java
data-service/src/main/java/com/nova/dataservice/service/LabReportLocationService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/LabReportLocationServiceImpl.java

Get All Reports By AppointmentId

NOVACARD-142

---

data-service/src/main/java/com/nova/dataservice/controller/LabReportLocation.java
data-service/src/main/java/com/nova/dataservice/entity/LabReportLocatiosn.java
data-service/src/main/java/com/nova/dataservice/repository/LabReportLocationReporitory.java
data-service/src/main/java/com/nova/dataservice/service/LabReportLocationService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/LabReportLocationServiceImpl.java

GetAllReportsByPatientIdAndLabIdAndCreatedAt

NOVACARD-141

---

data-service/src/main/java/com/nova/dataservice/DTO/AppoinmentDetailDTO.java
data-service/src/main/java/com/nova/dataservice/controller/AppointmentDetailsController.java
data-service/src/main/java/com/nova/dataservice/dao/AppointmentDetailDAO.java
data-service/src/main/java/com/nova/dataservice/daoimpl/AppoinmentDetailDaoImpl.java
data-service/src/main/java/com/nova/dataservice/service/AppointmentDetailservice.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/AppointmentDetailsserviceimpl.java
data-service/src/main/resources/application.yml

get past appointment by labId And patientId

NOVACARD-143

---

data-service/src/main/java/com/nova/dataservice/entity/UserDetails.java
data-service/src/main/resources/application.yml

Add Address column in user details table

NOVACARD-149

---

data-service/src/main/java/com/nova/dataservice/controller/ProfileUploadController.java
data-service/src/main/java/com/nova/dataservice/controller/ShopDetailsController.java
data-service/src/main/java/com/nova/dataservice/repository/ShopDetailsRepository.java
data-service/src/main/java/com/nova/dataservice/service/ShopDetailsService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/ShopDetailsServiceImpl.java

Upload logo In shopDeatailController
Upload AdharPhoto In userDetailController

NOVACARD -165&NOVACARD-169

---

data-service/src/main/java/com/nova/dataservice/controller/PunchInAndPunchOutController.java
data-service/src/main/java/com/nova/dataservice/entity/PunchInAndPunchOut.java
data-service/src/main/java/com/nova/dataservice/repository/PunchInAndPunchOutRepository.java
data-service/src/main/java/com/nova/dataservice/service/PunchInAndPunchOutService.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/PunchInAndPunchOutServiceImpl.java

created punchInAndPunchOut table
written API for savePunchIn
written API for updatedById
written API for updatedEmployeeIdAndDate

NOVACARD-190

---

data-service/src/main/java/com/nova/dataservice/DTO/ShopDetailsDTO.java
data-service/src/main/java/com/nova/dataservice/controller/BarCodeGenerateForLabController.java
data-service/src/main/java/com/nova/dataservice/controller/PdfLabReportGenaratorController.java
data-service/src/main/java/com/nova/dataservice/daoimpl/UserServiceDaoImpl.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/BarCodeGenerateForLabServiceImpl.java
data-service/src/main/java/com/nova/dataservice/utils/BarCodeGenUtils.java

QR Code is working fine as expected...Plz review this once

Update qr code pdf

---

data-service/src/main/java/com/nova/dataservice/controller/ProfileUploadController.java

NOVACARD-205:Validate file Formats for PDF, PNG, JPG

Validate file Formats for PDF, PNG, JPG

---

data-service/src/main/java/com/nova/dataservice/DTO/EachLabEariningByOwnerIdDTO.java
data-service/src/main/java/com/nova/dataservice/controller/AppointmentDetailsController.java
data-service/src/main/java/com/nova/dataservice/dao/AppointmentDetailDAO.java
data-service/src/main/java/com/nova/dataservice/daoimpl/AppoinmentDetailDaoImpl.java
data-service/src/main/java/com/nova/dataservice/service/AppointmentDetailservice.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/AppointmentDetailsserviceimpl.java

NOVACARD-183 : Get a earnings each LAB by owner ID

labEarningDetailsByOwnerId

---

data-service/src/main/java/com/nova/dataservice/controller/UserDetailsController.java
data-service/src/main/java/com/nova/dataservice/repository/UserDetailsRepository.java
data-service/src/main/java/com/nova/dataservice/service/UserDetailsServices.java
data-service/src/main/java/com/nova/dataservice/serviceImpl/UserDetailsServicesimpl.java
data-service/src/main/resources/application.yml

NOVACARD-236
